GET http://localhost:5000/users
Authorization: Bearer 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Afrizal3",
    "email": "Afrizal3@gmail.com",
    "password": "Afrizal1233",
    "confPassword": "Afrizal1233"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Afrizal2@gmail.com",
    "password": "Afrizal1233"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout